name: expense
networks:
  default:
    name: sulakaya

services:
    mysql:
      image: mysql:v.10.0
      container_name: mysql

    backend:
      image: backend:v.10.0
      container_name: backend
      depends_on: 
      - mysql

    frontend:
      image: frontend:v.10.0
      container_name: frontend
      depends_on: 
      - backend
      ports:
      - "80:80"

  

