name: expense
networks:
  default:
    name: pineapple
volumes:
  sudheer:

services:
    mysql:
      image: mysql:v.10.0
      container_name: mysql
      volumes:
      - source: sudheer
        target: /var/lib/mysql
        type: volume

    backend:
      image: backend:v.10.0
      container_name: backend
      command: sh -c "sleep 50 && node /opt/server/index.js"
      depends_on: 
      - mysql

    frontend:
      image: frontend:v.10.0
      container_name: frontend
      depends_on: 
      - backend
      ports:
      - "80:80"

  

